ATOM_NAME = Si
DIM = 4 4 4
PRIMITIVE_AXIS = auto
BAND = 0.0 0.0 0.0  0.5 0.5 0.5  0.5 0.25 0.75 0.5 0.0 0.5  0.0 0.0 0.0  
BAND_LABELS =$\Gamma$ L W X $\Gamma$
BAND_POINTS=1000
BAND_CONCENTION = .TRUE.
GROUP_VELOCITY = .TRUE.
WRITE_FORCE_CONSTANTS = .TRUE.
WRITEFC_FORMAT = HDF5

